name: dark_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^3.2.0
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.3+4


flutter:

  uses-material-design: true